### PR TITLE
organised into folders

### PR DESCRIPTION
**Pull request by Mani5871**
Separated all C++ and Java Codes into respective folders

### CODE REVIEW

**Review by striver79 — COMMENTED** [review]
can you please check one thing. 

Try creating a repo, add couple of files, get their github link. 
Then segregate them to two folders, and then see if the previous taken github link automatically redirects to the new link or not.

**Comment by Mani5871** [comment]
Yeah sure. I will try and get back to you.

**Comment by striver79** [comment]
This in turn means, I will have to go back and change all the links in every yt video, will be a very difficult thing..

**Comment by Mani5871** [comment]
I understood the problem. No issues😊

**Pull request closed without merging**
